# Generated by Django 6.0.3 on 2026-04-27 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(default='Diagnostico general', max_length=100)),
                ('stability', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('deviation_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('alignment', models.CharField(default='Sin determinar', max_length=50)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=255, verbose_name='1. ¿Ha sufrido alguna caída en los últimos 12 meses?')),
                ('q2', models.CharField(max_length=255, verbose_name='2. ¿Siente miedo a caerse al caminar dentro de casa?')),
                ('q3', models.CharField(max_length=255, verbose_name='3. ¿Utiliza algún apoyo para caminar (bastón, andador)?')),
                ('q4', models.CharField(max_length=255, verbose_name='4. ¿Siente mareos o pérdida de equilibrio al levantarse de una silla?')),
                ('q5', models.CharField(max_length=255, verbose_name='5. ¿Realiza alguna actividad física de forma regular?')),
                ('q6', models.CharField(max_length=255, verbose_name='6. ¿Cuántos días a la semana camina por lo menos 15 minutos seguidos?')),
                ('q7', models.CharField(max_length=255, verbose_name='7. ¿Tiene problemas de visión que no estén corregidos por gafas?')),
                ('q8', models.CharField(max_length=255, verbose_name='8. ¿Toma 3 o más medicamentos diariamente?')),
                ('q9', models.CharField(max_length=255, verbose_name='9. ¿Siente debilidad o falta de fuerza en las piernas?')),
                ('q10', models.CharField(max_length=255, verbose_name='10. ¿Tiene dolor en las articulaciones (rodillas, caderas, tobillos) al moverse?')),
                ('q11', models.CharField(max_length=255, verbose_name='11. ¿Evita salir de casa por miedo a caerse?')),
                ('q12', models.CharField(max_length=255, verbose_name='12. ¿Alguna vez ha necesitado ayuda para levantarse del suelo después de una caída?')),
                ('q13', models.CharField(max_length=255, verbose_name='13. ¿Su casa tiene obstáculos como alfombras sueltas, cables o poca iluminación?')),
                ('q14', models.CharField(max_length=255, verbose_name='14. ¿Conoce qué tipos de ejercicios ayudan a mejorar el equilibrio?')),
                ('q15', models.CharField(max_length=255, verbose_name='15. ¿Le gustaría recibir un plan de ejercicios para mejorar su estabilidad?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
