# Generated by Django 6.0.3 on 2026-04-29 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_doctoradvice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoradvice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Determina si el consejo se muestra en la web'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='deviation_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desviacion lateral en cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calidad de la captura de video', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='stability',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de estabilidad', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='test_type',
            field=models.CharField(default='Diagnostico general', help_text='Ej: Marcha Tandem', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patient_data',
            field=models.TextField(blank=True, default='', help_text='Antecedentes y alergias'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora de la cita')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo de la consulta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas médicas')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
