# Generated by Django 6.0.3 on 2026-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_doctoradvice_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, default='Medicina General', help_text='Especialidad médica', max_length=100),
        ),
    ]
