# Generated by Django 6.0.3 on 2026-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_profile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[('Hijo/a', 'Hijo/a'), ('Hermano/a', 'Hermano/a'), ('Esposo/a', 'Esposo/a'), ('Padre/Madre', 'Padre o Madre'), ('Otro', 'Otro')], default='', max_length=100),
        ),
    ]
