# Generated by Django 6.0.3 on 2026-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de Identidad'),
        ),
    ]
