# Generated by Django 6.0.3 on 2026-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_profile_ci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationForm',
        ),
    ]
