# Generated by Django 6.0.8 on 2026-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_question_patientanswer_delete_patientquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='¿Cita concluida?'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='doctoradvice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='doctoradvice',
            name='message',
            field=models.TextField(verbose_name='Recomendación Médica'),
        ),
        migrations.AlterField(
            model_name='doctoradvice',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título del Consejo'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='alignment',
            field=models.CharField(default='Sin determinar', help_text='Estado de alineación postural', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='deviation_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desviación lateral en centímetros', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje de calidad de video/captura', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='stability',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de estabilidad (0 a 100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='test_type',
            field=models.CharField(default='Diagnóstico general', help_text='Ej: Marcha Tandem, Soporte Monopodal', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientanswer',
            name='response',
            field=models.CharField(max_length=255, verbose_name='Elección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección del Familiar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo del Familiar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del Familiar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular del Familiar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[('Hijo/a', 'Hijo/a'), ('Hermano/a', 'Hermano/a'), ('Esposo/a', 'Esposo/a'), ('Padre/Madre', 'Padre o Madre'), ('Otro', 'Otro')], default='', max_length=100, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patient_data',
            field=models.TextField(blank=True, default='', help_text='Antecedentes, enfermedades previas y alergias'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono/Celular'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar al paciente?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Pregunta de Salud'),
        ),
    ]
